[build-system]
requires = ["maturin>=1.1,<2.0"]
build-backend = "maturin"

[project]
name = "pyo3-test"
classifiers = [
    "Programming Language :: Rust"
]

[tool.maturin]
features = ["pyo3", "pyo3/extension-module"]

